const firebaseConfig={apiKey:"AIzaSyB6m0Yis89jxvm06OFBqxs8P_vADjRXk0U",authDomain:"video-poker-6d665.firebaseapp.com",projectId:"video-poker-6d665",storageBucket:"video-poker-6d665.firebasestorage.app",messagingSenderId:"53702406091",appId:"1:53702406091:web:1ef4969a8cc77ebd6a504e"};
firebase.initializeApp(firebaseConfig);const auth=firebase.auth(),$=id=>document.getElementById(id);let projects=[],googleToken=sessionStorage.getItem('firebasePortfolioGoogleToken')||'',loadedUser=null;
auth.onAuthStateChanged(async user=>{loadedUser=user;await showAuthenticatedUser()});
async function showAuthenticatedUser(){const user=loadedUser;if(!user){showLogin();return}if((user.email||'').toLowerCase()!=='micorlov@gmail.com'){await auth.signOut();sessionStorage.removeItem('firebasePortfolioGoogleToken');$("login-error").textContent='Only micorlov@gmail.com can access this panel.';return}$("login").hidden=true;$("dashboard").hidden=false;$("user-email").textContent=user.email;if(googleToken&&!projects.length)await loadData();else if(!googleToken)$("error").textContent='Signed in, but Google API access was not granted. Click Refresh after granting read-only access.'}
$("google-login").onclick=async()=>{try{const provider=new firebase.auth.GoogleAuthProvider();const result=await auth.signInWithPopup(provider),credential=firebase.auth.GoogleAuthProvider.credentialFromResult(result);googleToken=credential?.accessToken||'';sessionStorage.setItem('firebasePortfolioGoogleToken',googleToken);loadedUser=result.user;await showAuthenticatedUser()}catch(e){$("login-error").textContent=e.message.replace('Firebase: ','')}};$("sign-out").onclick=()=>{sessionStorage.removeItem('firebasePortfolioGoogleToken');googleToken='';auth.signOut()};$("refresh").onclick=loadData;$("search").oninput=render;
function showLogin(){$("login").hidden=false;$("dashboard").hidden=true}
async function api(url,options={}){const r=await fetch(url,{...options,headers:{Authorization:`Bearer ${googleToken}`,'Content-Type':'application/json',...(options.headers||{})}});if(!r.ok)throw Error(`${r.status} ${r.statusText}`);return r.json()}
async function all(url,field){let out=[],page='';do{const join=url.includes('?')?'&':'?',x=await api(`${url}${join}pageSize=100${page?`&pageToken=${encodeURIComponent(page)}`:''}`);out.push(...(x[field]||[]));page=x.nextPageToken||''}while(page);return out}
async function users(propertyId){if(!propertyId)return null;try{const x=await api(`https://analyticsdata.googleapis.com/v1beta/properties/${propertyId}:runReport`,{method:'POST',body:JSON.stringify({dateRanges:[{startDate:'yesterday',endDate:'yesterday'}],metrics:[{name:'activeUsers'}]})});return Number(x.rows?.[0]?.metricValues?.[0]?.value||0)}catch(e){return null}}
async function project(p){const name=`projects/${p.projectId}`;const [apps,a]=await Promise.all([all(`https://firebase.googleapis.com/v1beta1/${name}:searchApps`,'apps'),api(`https://firebase.googleapis.com/v1beta1/${name}/analyticsDetails`).catch(()=>null)]);const propertyId=a?.propertyId||a?.property?.replace('properties/','')||null;return{projectId:p.projectId,displayName:p.displayName||p.projectId,apps:apps.map(x=>({name:x.displayName||x.appId,platform:x.platform||x.name?.split('/')[2]?.replace('Apps','')||'UNKNOWN'})),analytics:propertyId?{dailyUsers:await users(propertyId)}:null}}
async function loadData(){$("refresh").disabled=true;$("refresh").textContent='Loading…';$("error").textContent='';try{const ps=await all('https://firebase.googleapis.com/v1beta1/projects','results'),done=await Promise.allSettled(ps.map(project));projects=done.map((x,i)=>x.status==='fulfilled'?x.value:{projectId:ps[i].projectId,displayName:ps[i].displayName||ps[i].projectId,apps:[],analytics:null,error:x.reason.message});$("updated").textContent=`Updated ${new Date().toLocaleString()}`;render()}catch(e){$("error").textContent=`Could not load Firebase data: ${e.message}. Sign out and sign in again to grant read-only Google API access.`}finally{$("refresh").disabled=false;$("refresh").textContent='Refresh'}}
function render(){const q=$("search").value.toLowerCase(),visible=projects.filter(p=>`${p.displayName} ${p.projectId} ${p.apps.map(a=>a.name).join(' ')}`.toLowerCase().includes(q)),apps=projects.flatMap(p=>p.apps),linked=projects.filter(p=>p.analytics),users=projects.reduce((n,p)=>n+(p.analytics?.dailyUsers||0),0);$("project-count").textContent=projects.length.toLocaleString();$("app-count").textContent=apps.length.toLocaleString();$("user-count").textContent=users.toLocaleString();$("analytics-count").textContent=`${linked.length}/${projects.length}`;$("projects").innerHTML=visible.map(p=>{const platforms=[...new Set(p.apps.map(a=>a.platform.toLowerCase()))];return `<tr><td><div class="project-name">${esc(p.displayName)}</div><div class="project-id">${esc(p.projectId)}</div></td><td>${p.apps.length}</td><td><div class="platforms">${platforms.length?platforms.map(x=>`<span class="tag">${esc(x)}</span>`).join(''):'<span class="muted">No apps</span>'}</div></td><td class="metric">${p.analytics?.dailyUsers==null?'<span class="muted">Unavailable</span>':p.analytics.dailyUsers.toLocaleString()}</td><td>${p.analytics?'<span class="tag">Linked</span>':'<span class="muted">Not linked</span>'}</td></tr>`}).join('')||'<tr><td colspan="5" class="muted">No matching projects.</td></tr>'}function esc(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
